export type GigyaDataCenter =
    | 'us1.gigya.com'
    | 'eu1.gigya.com'
    | 'au1.gigya.com'
    | 'eu2.gigya.com'
    | 'cn1.sapcdm.cn'
    | 'global.gigya.com';

export type GigyaRegion = 'us1' | 'eu1' | 'au1' | 'cn1';

export type GigyaRequest<T> = T & CommonRequestParams;

export type GigyaResponse<T> = T & CommonResponseParams;

/**
 * This is a generic interface which is used to extend pretty much every request to Gigya.
 * It contains common request parameters that are shared everywhere.
 */
export type CommonRequestParams = {
    /**
     * A string of maximum 100 characters length. The CID sets categories for transactions that can be used later for
     * filtering reports generated by SAP Customer Data CloudInformation published on non-SAP site in the "Context ID"
     * combo box. The CID allows you to associate the report information with your own internal data. For example,
     * to identify a specific widget or page on your site/application. You should not define more than 100 different
     * context IDs.
     *
     * Note: This parameter overrides the value of the identical parameter in Global Conf (the global configuration
     * object). If the parameter is not set for the method, the value from Global Conf is used.
     */
    cid?: string;
    /**
     * A developer-created object that is passed back unchanged to the application as one of the fields in the
     * response object.
     */
    context?: string;
    /**
     * The default value of this parameter is false, which means that the HTTP status code in Gigya's response
     * sis always 200 (OK), even if an error occurs. The error code and message is given within the response
     * data (see below). If this parameter is set to true, the HTTP status code in Gigya's response would reflect
     * an error, if one occurred.
     */
    httpStatusCodes?: boolean;
};

export interface CommonResponseParams {
    /**
     * Defines the API version that returned the response.
     */
    apiVersion: number;
    /**
     * Unique identifier of the transaction, for debugging purposes.
     */
    callId: string;
    /**
     * The result code of the operation. Code '0' indicates success, any other number indicates failure.
     * For a complete list of error codes, see the
     * {@link https://help.sap.com/docs/SAP_CUSTOMER_DATA_CLOUD/8b8d6fffe113457094a17701f63e3d6a/416d41b170b21014bbc5a10ce4041860.html Response Codes and Errors}
     * table.
     */
    errorCode: number;
    errorDetails: string;
    /**
     * A short textual description of an error associated with the errorCode for logging purposes.
     */
    errorMessage: string;
    statusCode: number;
    statusReason: string;
    time: string;
    context?: string;
}
